In [1]:
import numpy as np
import pandas as pd
print("numpy version:",np.__version__)
print("pandas version:",pd.__version__)

numpy version: 2.5.1
pandas version: 3.0.3

In [2]:
df=pd.read_csv("../data/ncr_ride_bookings.csv")

In [3]:
df.head()# check 5 row of data set

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,NaN,NaN,NaN,1.0,Vehicle Breakdown,237.0,5.73,NaN,NaN,UPI
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,NaN,NaN,NaN,NaN,NaN,627.0,13.58,4.9,4.9,Debit Card
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,NaN,NaN,NaN,NaN,NaN,416.0,34.02,4.6,5.0,UPI
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,NaN,NaN,NaN,NaN,NaN,737.0,48.21,4.1,4.3,UPI

In [4]:
df.info()# check all information about dataset

<class 'pandas.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 21 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Date                               150000 non-null  str
 1   Time                               150000 non-null  str
 2   Booking ID                         150000 non-null  str
 3   Booking Status                     150000 non-null  str
 4   Customer ID                        150000 non-null  str
 5   Vehicle Type                       150000 non-null  str
 6   Pickup Location                    150000 non-null  str
 7   Drop Location                      150000 non-null  str
 8   Avg VTAT                           139500 non-null  float64
 9   Avg CTAT                           102000 non-null  float64
 10  Cancelled Rides by Customer        10500 non-null   float64
 11  Reason for cancelling by Customer  10500 non-null   str
 12  Cancelled Rides by Driver          27000 non-null   float64
 13  Driver Cancellation Reason         27000 non-null   str
 14  Incomplete Rides                   9000 non-null    float64
 15  Incomplete Rides Reason            9000 non-null    str
 16  Booking Value                      102000 non-null  float64
 17  Ride Distance                      102000 non-null  float64
 18  Driver Ratings                     93000 non-null   float64
 19  Customer Rating                    93000 non-null   float64
 20  Payment Method                     102000 non-null  str
dtypes: float64(9), str(12)
memory usage: 24.0 MB

In [5]:
#check null value of dataset
df.isnull().sum()

Date                                      0
Time                                      0
Booking ID                                0
Booking Status                            0
Customer ID                               0
Vehicle Type                              0
Pickup Location                           0
Drop Location                             0
Avg VTAT                              10500
Avg CTAT                              48000
Cancelled Rides by Customer          139500
Reason for cancelling by Customer    139500
Cancelled Rides by Driver            123000
Driver Cancellation Reason           123000
Incomplete Rides                     141000
Incomplete Rides Reason              141000
Booking Value                         48000
Ride Distance                         48000
Driver Ratings                        57000
Customer Rating                       57000
Payment Method                        48000
dtype: int64

In [6]:
#to count the number of cutomer canecellation and missing values in this column.
#df["Cancelled Rides by Customer"] --> Selects the Cancelled Rides by Customer column.
#value_counts() counts the frequency of each unique value in a column.
#dropna=False --> Includes missing (NaN) values in the count.
df['Cancelled Rides by Customer'].value_counts(dropna=False)

Cancelled Rides by Customer
NaN    139500
1.0     10500
Name: count, dtype: int64

In [7]:
#to count the number of driver canecellation and missing values in this column.
#df["Cancelled Rides by Driver"] --> Selects the Cancelled Rides by Driver column.
#value_counts() counts the frequency of each unique value in a column.
#dropna=False --> Includes missing (NaN) values in the count.
df["Cancelled Rides by Driver"].value_counts(dropna=False)

Cancelled Rides by Driver
NaN    123000
1.0     27000
Name: count, dtype: int64

In [8]:
df["Incomplete Rides"].value_counts(dropna=False)
#to count the number of incomplete rise  and missing values in this column.
#df["Incomplete Rides"] --> Selects the incomplete-rides column.
#.value_counts() --> Counts how many times each value appears.
#dropna=False --> Includes missing (NaN) values in the count.

Incomplete Rides
NaN    141000
1.0      9000
Name: count, dtype: int64

In [9]:
df["Booking Status"].value_counts(dropna=False)
#df["Booking Status"] --> Selects the Booking Status column.
#.value_counts() --> Counts how many times each status appears.
#dropna=False --> Includes missing values in the count.

Booking Status
Completed                93000
Cancelled by Driver      27000
No Driver Found          10500
Cancelled by Customer    10500
Incomplete                9000
Name: count, dtype: int64

In [10]:
df.duplicated().sum()
#df.duplicated().sum() --> return  the total  duplicated rows in a DataFrame.
#df.duplicated() --> Identifies rows that are exact duplicates of previous rows.
#.sum() --> Counts how many duplicate rows were found

np.int64(0)

In [11]:
df.columns
#df.columns --> Returns the names of all columns in the DataFrame.

Index(['Date', 'Time', 'Booking ID', 'Booking Status', 'Customer ID',
       'Vehicle Type', 'Pickup Location', 'Drop Location', 'Avg VTAT',
       'Avg CTAT', 'Cancelled Rides by Customer',
       'Reason for cancelling by Customer', 'Cancelled Rides by Driver',
       'Driver Cancellation Reason', 'Incomplete Rides',
       'Incomplete Rides Reason', 'Booking Value', 'Ride Distance',
       'Driver Ratings', 'Customer Rating', 'Payment Method'],
      dtype='str')

In [12]:
df.dtypes
#df.dtypes --> Shows the data type of every column in a DataFrame

Date                                     str
Time                                     str
Booking ID                               str
Booking Status                           str
Customer ID                              str
Vehicle Type                             str
Pickup Location                          str
Drop Location                            str
Avg VTAT                             float64
Avg CTAT                             float64
Cancelled Rides by Customer          float64
Reason for cancelling by Customer        str
Cancelled Rides by Driver            float64
Driver Cancellation Reason               str
Incomplete Rides                     float64
Incomplete Rides Reason                  str
Booking Value                        float64
Ride Distance                        float64
Driver Ratings                       float64
Customer Rating                      float64
Payment Method                           str
dtype: object

In [13]:
df["Date"].head(10)
#df["Date"] --> Selects the Date column.
#.head(10) --> Displays the first 10 values from that column.

0    2024-03-23
1    2024-11-29
2    2024-08-23
3    2024-10-21
4    2024-09-16
5    2024-02-06
6    2024-06-17
7    2024-03-19
8    2024-09-14
9    2024-12-16
Name: Date, dtype: str

In [14]:
df["Time"].head(10)
#df["Time"] → Selects the Time column from the DataFrame.
#.head(10) → Displays the first 10 values of that column.

0    12:29:38
1    18:01:39
2    08:56:10
3    17:17:25
4    22:08:00
5    09:44:56
6    15:45:58
7    17:37:37
8    12:49:09
9    19:06:48
Name: Time, dtype: str

In [15]:
df["Date"] = pd.to_datetime(df["Date"])
df["Date"].dtype
#pd.to_datetime() --> Converts a column into Pandas datetime format.
#df["Date"] = --> Stores the converted values back into the Date column.
#.dtype-->Shows the data type of a column.

dtype('<M8[us]')

In [16]:
df["Time"] = pd.to_datetime(df["Time"], format="%H:%M:%S").dt.time
df["Time"].dtype
#pd.to_datetime() --> Converts text into a datetime format.
#format="%H:%M:%S" --> Tells Pandas that the time is in Hour:Minute:Second format.
#.dt.time --> Extracts only the time portion.

dtype('O')

In [17]:
df["Time"].head(10)

0    12:29:38
1    18:01:39
2    08:56:10
3    17:17:25
4    22:08:00
5    09:44:56
6    15:45:58
7    17:37:37
8    12:49:09
9    19:06:48
Name: Time, dtype: object

In [18]:
df["Booking Value"].describe()
#describe() --> Provides statistical summary such as count, mean, minimum, maximum, and quartiles for a numeric column.

count    102000.000000
mean        508.295912
std         395.805774
min          50.000000
25%         234.000000
50%         414.000000
75%         689.000000
max        4277.000000
Name: Booking Value, dtype: float64

Count: 102,000 non-null values,
Minimum: ₹50,
Maximum: ₹4,277,
Mean: ~₹508.30,
Median: ₹414,

In [19]:
df["Ride Distance"].describe()

count    102000.000000
mean         24.637012
std          14.002138
min           1.000000
25%          12.460000
50%          23.720000
75%          36.820000
max          50.000000
Name: Ride Distance, dtype: float64

Count: 102,000
Mean: ~24.64 km,
Minimum: 1 km,
Maximum: 50 km,
Median: 23.72 km,
Negative values: no,
Zero values: no,

In [20]:
df["Driver Ratings"].describe()

count    93000.000000
mean         4.230992
std          0.436871
min          3.000000
25%          4.100000
50%          4.300000
75%          4.600000
max          5.000000
Name: Driver Ratings, dtype: float64

Count: 93,000,
Mean: ~4.23,
Minimum: 3.0,
Maximum: 5.0,
Median: 4.3,
Negative/invalid values: no

In [21]:
df["Customer Rating"].describe()

count    93000.000000
mean         4.404584
std          0.437819
min          3.000000
25%          4.200000
50%          4.500000
75%          4.800000
max          5.000000
Name: Customer Rating, dtype: float64

Count: 93,000,
Mean: ~4.40,
Minimum: 3.0,
Maximum: 5.0,
Median: 4.5,
Invalid/negative values: no

In [22]:
df["Payment Method"].value_counts(dropna=False)

Payment Method
NaN            48000
UPI            45909
Cash           25367
Uber Wallet    12276
Credit Card    10209
Debit Card      8239
Name: count, dtype: int64

48,000 Payment Method values missing

In [23]:
pd.crosstab(df["Booking Status"], df["Payment Method"], dropna=False)
#pd.crosstab() → Creates a frequency table showing the relationship between two categorical columns

Payment Method,Cash,Credit Card,Debit Card,UPI,Uber Wallet,NaN
Booking Status,,,,,,
Cancelled by Customer,0,0,0,0,0,10500
Cancelled by Driver,0,0,0,0,0,27000
Completed,23114,9320,7526,41834,11206,0
Incomplete,2253,889,713,4075,1070,0
No Driver Found,0,0,0,0,0,10500

Cancelled by Customer --> 10,500 missing,
Cancelled by Driver --> 27,000 missing,
No Driver Found --> 10,500 missing,
Completed --> 0 missing,
Incomplete --> 0 missing

In [24]:
df["Pickup Location"].value_counts(dropna=False)

Pickup Location
Khandsa             949
Barakhamba Road     946
Saket               931
Badarpur            921
Pragati Maidan      920
                   ...
Chirag Delhi        800
Noida Sector 18     799
Laxmi Nagar         797
Ashok Vihar         796
Ghitorni Village    790
Name: count, Length: 176, dtype: int64

## 3.4 Pickup Location Analysis

The pickup location column is analyzed to identify the distribution of ride bookings across different locations and to check for missing values.

In [25]:
df["Drop Location"].value_counts(dropna=False)

Drop Location
Ashram              936
Basai Dhankot       917
Lok Kalyan Marg     916
Narsinghpur         913
Cyber Hub           912
                   ...
MG Road             799
Bhiwadi             792
Shivaji Park        786
Anand Vihar ISBT    784
Huda City Centre    774
Name: count, Length: 176, dtype: int64

##  Drop Location Analysis

The drop location column is analyzed to understand the distribution of ride destinations and to identify any missing values.

In [26]:
df["Vehicle Type"].value_counts(dropna=False)

Vehicle Type
Auto             37419
Go Mini          29806
Go Sedan         27141
Bike             22517
Premier Sedan    18111
eBike            10557
Uber XL           4449
Name: count, dtype: int64

##  Vehicle Type Analysis

The vehicle type column is analyzed to identify the different vehicle categories used for ride bookings and their booking frequency.

In [27]:
df["Booking ID"].nunique()
#nunique() --> Counts the number of unique values in a column

148767

##  Booking ID Uniqueness Check

The booking ID is checked to identify duplicate booking identifiers and ensure that each ride has a unique booking ID.

In [28]:
df["Booking ID"].duplicated().sum()
#duplicated() --> Identifies values that have already appeared earlier in the

np.int64(1233)

### Duplicate Booking ID Check

The booking ID is checked to identify how many booking identifiers appear more than once in the dataset.

In [29]:
df["Customer ID"].nunique()

148788

##  Customer ID Uniqueness Check

The customer ID is checked to identify the number of unique customers in the dataset.

In [30]:
df["Customer ID"].nunique()

148788

In [31]:
print("Total rows:", len(df))
print("Unique Customer IDs:", df["Customer ID"].nunique())
print("Missing Customer IDs:", df["Customer ID"].isnull().sum())
print("Non-missing Customer IDs:", df["Customer ID"].notnull().sum())

Total rows: 150000
Unique Customer IDs: 148788
Missing Customer IDs: 0
Non-missing Customer IDs: 150000

In [32]:
df["Reason for cancelling by Customer"].value_counts(dropna=False)

Reason for cancelling by Customer
NaN                                             139500
Wrong Address                                     2362
Change of plans                                   2353
Driver is not moving towards pickup location      2335
Driver asked to cancel                            2295
AC is not working                                 1155
Name: count, dtype: int64

## Customer Cancellation Reason Analysis

The customer cancellation reason column is analyzed to identify the reasons associated with customer-cancelled rides.

In [33]:
df["Driver Cancellation Reason"].value_counts(dropna=False)

Driver Cancellation Reason
NaN                                    123000
Customer related issue                   6837
The customer was coughing/sick           6751
Personal & Car related issues            6726
More than permitted people in there      6686
Name: count, dtype: int64

##  Driver Cancellation Reason Analysis

The driver cancellation reason column is analyzed to identify the reasons associated with driver-cancelled rides.

In [34]:
df["Incomplete Rides Reason"].value_counts(dropna=False)

Incomplete Rides Reason
NaN                  141000
Customer Demand        3040
Vehicle Breakdown      3012
Other Issue            2948
Name: count, dtype: int64

##  Incomplete Ride Reason Analysis

The incomplete ride reason column is analyzed to identify the reasons associated with incomplete rides.

In [35]:
df["Avg VTAT"].describe()

count    139500.000000
mean          8.456352
std           3.773564
min           2.000000
25%           5.300000
50%           8.300000
75%          11.300000
max          20.000000
Name: Avg VTAT, dtype: float64

##  Average VTAT Analysis

The average vehicle time of arrival is analyzed to understand vehicle arrival time and identify unusual values.

In [36]:
df["Avg CTAT"].describe()

count    102000.000000
mean         29.149636
std           8.902577
min          10.000000
25%          21.600000
50%          28.800000
75%          36.800000
max          45.000000
Name: Avg CTAT, dtype: float64

##  Average CTAT Analysis

The average customer time of arrival is analyzed to understand customer waiting time and identify unusual values.

In [37]:
df["Booking Value"].describe()

count    102000.000000
mean        508.295912
std         395.805774
min          50.000000
25%         234.000000
50%         414.000000
75%         689.000000
max        4277.000000
Name: Booking Value, dtype: float64

In [38]:
df["Date"].min(), df["Date"].max()

(Timestamp('2024-01-01 00:00:00'), Timestamp('2024-12-30 00:00:00'))

##  Date Range Analysis

The booking date column is analyzed to identify the minimum and maximum dates covered by the dataset.

In [39]:
df["Time"].describe()

count       150000
unique       62910
top       17:44:57
freq            16
Name: Time, dtype: object

## Booking Time Analysis

The booking time column is analyzed to understand the distribution of ride bookings throughout the day.

In [40]:
#  This checks text columns for empty or whitespace-only values.

text_columns = df.select_dtypes(include="object").columns

blank_counts = {}

for col in text_columns:
    blank_counts[col] = df[col].astype(str).str.strip().eq("").sum()

pd.Series(blank_counts)


#text_columns → dataset ke text/object columns select karega.
#.str.strip() → extra spaces hata kar check karega.
#.eq("") → dekhega value completely blank hai ya nahi.
#Last me har column ke blank values ka count milega.

C:\Users\asus\AppData\Local\Temp\ipykernel_21312\2831463297.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  text_columns = df.select_dtypes(include="object").columns

Time                                 0
Booking ID                           0
Booking Status                       0
Customer ID                          0
Vehicle Type                         0
Pickup Location                      0
Drop Location                        0
Reason for cancelling by Customer    0
Driver Cancellation Reason           0
Incomplete Rides Reason              0
Payment Method                       0
dtype: int64

## Blank Text Value Analysis

The text columns are checked for empty or whitespace-only values that may not be detected as missing values.

In [41]:
# This identifies booking IDs that appear more than once and counts their occurrences.

booking_id_counts = df["Booking ID"].value_counts()

repeated_booking_ids = booking_id_counts[booking_id_counts > 1]

repeated_booking_ids.head(20)

Booking ID
"CNR7908610"    3
"CNR9603232"    3
"CNR3648267"    3
"CNR2726142"    3
"CNR7199036"    3
"CNR7585544"    3
"CNR7642097"    3
"CNR5292943"    3
"CNR6337479"    3
"CNR2687237"    2
"CNR5380412"    2
"CNR5071968"    2
"CNR2290384"    2
"CNR3466923"    2
"CNR5743864"    2
"CNR6919794"    2
"CNR7417664"    2
"CNR1197334"    2
"CNR3011900"    2
"CNR6977914"    2
Name: count, dtype: int64

## Repeated Booking ID Analysis

The booking ID column is analyzed to identify repeated booking IDs and determine their frequency in the dataset.

In [42]:
# Definition: This filters the dataset and displays all records for the selected booking ID.

df[df["Booking ID"] == "CNR7908610"]

Empty DataFrame
Columns: [Date, Time, Booking ID, Booking Status, Customer ID, Vehicle Type, Pickup Location, Drop Location, Avg VTAT, Avg CTAT, Cancelled Rides by Customer, Reason for cancelling by Customer, Cancelled Rides by Driver, Driver Cancellation Reason, Incomplete Rides, Incomplete Rides Reason, Booking Value, Ride Distance, Driver Ratings, Customer Rating, Payment Method]
Index: []

[0 rows x 21 columns]

##  Repeated Booking ID Record Comparison

A repeated booking ID is examined to compare its associated records and determine whether the repeated entries contain different booking information.

In [43]:
# Definition: This selects the first repeated booking ID directly from the dataset.

selected_booking_id = repeated_booking_ids.index[0]

print("Selected Booking ID:", selected_booking_id)

df[df["Booking ID"] == selected_booking_id]

Selected Booking ID: "CNR7908610"

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Reason for cancelling by Customer,Cancelled Rides by Driver,Driver Cancellation Reason,Incomplete Rides,Incomplete Rides Reason,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method
2390,2024-03-26,15:54:11,"""CNR7908610""",Completed,"""CID7755899""",Uber XL,Satguru Ram Singh Marg,Bahadurgarh,9.0,22.7,...,NaN,NaN,NaN,NaN,NaN,707.0,34.64,3.8,4.8,Cash
105065,2024-09-03,19:38:29,"""CNR7908610""",Completed,"""CID5251969""",Go Mini,Saket A Block,Keshav Puram,13.3,36.0,...,NaN,NaN,NaN,NaN,NaN,456.0,27.73,4.6,4.7,Cash
130690,2024-12-30,07:01:22,"""CNR7908610""",Completed,"""CID3266637""",Bike,Bhikaji Cama Place,Mandi House,7.5,38.3,...,NaN,NaN,NaN,NaN,NaN,495.0,27.70,4.8,3.9,UPI

In [44]:
# Definition: This counts zero values in selected numeric columns.

numeric_columns = [
    "Avg VTAT",
    "Avg CTAT",
    "Booking Value",
    "Ride Distance",
    "Driver Ratings",
    "Customer Rating"
]

zero_counts = (df[numeric_columns] == 0).sum()

zero_counts

Avg VTAT           0
Avg CTAT           0
Booking Value      0
Ride Distance      0
Driver Ratings     0
Customer Rating    0
dtype: int64

## Zero Value Analysis

The numeric columns are checked for zero values to identify potentially invalid or unusual records before data cleaning.

In [45]:
# Definition: This counts negative values in selected numeric columns.

negative_counts = (df[numeric_columns] < 0).sum()

negative_counts

Avg VTAT           0
Avg CTAT           0
Booking Value      0
Ride Distance      0
Driver Ratings     0
Customer Rating    0
dtype: int64

## Negative Value Analysis

The numeric columns are checked for negative values to identify potentially invalid records before data cleaning.

In [46]:
# Definition: This counts ratings that fall outside the expected range of 3 to 5.

rating_columns = ["Driver Ratings", "Customer Rating"]

invalid_rating_counts = (
    (df[rating_columns] < 3) | (df[rating_columns] > 5)
).sum()

invalid_rating_counts

Driver Ratings     0
Customer Rating    0
dtype: int64

##  Rating Range Validation

The driver and customer rating columns are checked to identify values outside the expected rating range of 3 to 5.

In [47]:
# Definition: This compares the availability of booking values across different booking statuses.

booking_value_status = pd.crosstab(
    df["Booking Status"],
    df["Booking Value"].isna()
)

booking_value_status

Booking Value          False  True
Booking Status
Cancelled by Customer      0  10500
Cancelled by Driver        0  27000
Completed              93000      0
Incomplete              9000      0
No Driver Found            0  10500

## Booking Value Availability by Booking Status

The availability of booking value is analyzed across different booking statuses to understand which ride outcomes contain financial information.

In [48]:
# Definition: This compares the availability of ride distance across different booking statuses.

ride_distance_status = pd.crosstab(
    df["Booking Status"],
    df["Ride Distance"].isna()
)

ride_distance_status

Ride Distance          False  True
Booking Status
Cancelled by Customer      0  10500
Cancelled by Driver        0  27000
Completed              93000      0
Incomplete              9000      0
No Driver Found            0  10500

##  Ride Distance Availability by Booking Status

The availability of ride distance is analyzed across different booking statuses to understand which ride outcomes contain trip distance information.

In [49]:
# Definition: This compares the availability of operational time metrics across booking statuses.

operational_metrics_status = pd.DataFrame({
    "Missing Avg VTAT": df.groupby("Booking Status")["Avg VTAT"].apply(lambda x: x.isna().sum()),
    "Missing Avg CTAT": df.groupby("Booking Status")["Avg CTAT"].apply(lambda x: x.isna().sum())
})

operational_metrics_status

                       Missing Avg VTAT  Missing Avg CTAT
Booking Status
Cancelled by Customer                 0             10500
Cancelled by Driver                   0             27000
Completed                             0                 0
Incomplete                            0                 0
No Driver Found                   10500             10500

## Operational Metrics Availability by Booking Status

The availability of vehicle arrival time and customer trip time is analyzed across different booking statuses to understand which operational metrics are recorded for each ride outcome.

In [50]:

# Definition: This compares the availability of driver and customer ratings across booking statuses.

rating_status = pd.DataFrame({
    "Missing Driver Ratings": df.groupby("Booking Status")["Driver Ratings"].apply(lambda x: x.isna().sum()),
    "Missing Customer Ratings": df.groupby("Booking Status")["Customer Rating"].apply(lambda x: x.isna().sum())
})

rating_status

                       Missing Driver Ratings  Missing Customer Ratings
Booking Status
Cancelled by Customer                   10500                     10500
Cancelled by Driver                     27000                     27000
Completed                                   0                         0
Incomplete                               9000                      9000
No Driver Found                         10500                     10500

##  Rating Availability by Booking Status

The availability of driver and customer ratings is analyzed across different booking statuses to understand which ride outcomes contain rating information.

In [51]:
# Definition: This checks whether reason fields contain values for booking statuses where they should not apply.

reason_columns = [
    "Reason for cancelling by Customer",
    "Driver Cancellation Reason",
    "Incomplete Rides Reason"
]

reason_presence = pd.DataFrame({
    col: df.groupby("Booking Status")[col].apply(lambda x: x.notna().sum())
    for col in reason_columns
})

reason_presence

,Reason for cancelling by Customer,Driver Cancellation Reason,Incomplete Rides Reason
Booking Status,,,
Cancelled by Customer,10500,0,0
Cancelled by Driver,0,27000,0
Completed,0,0,0
Incomplete,0,0,9000
No Driver Found,0,0,0

##  Cancellation and Incomplete Reason Consistency

The cancellation and incomplete ride reason columns are checked against booking status to identify any inconsistent reason values.

In [52]:
# Definition: This counts available payment methods for each booking status.

payment_status = df.groupby("Booking Status")["Payment Method"].apply(
    lambda x: x.notna().sum()
)

payment_status

Booking Status
Cancelled by Customer        0
Cancelled by Driver          0
Completed                93000
Incomplete                9000
No Driver Found              0
Name: Payment Method, dtype: int64

In [53]:
# Definition: This creates a compact summary of the dataset's key structural quality metrics.

data_quality_summary = pd.Series({
    "Total Rows": len(df),
    "Total Columns": df.shape[1],
    "Duplicate Rows": df.duplicated().sum(),
    "Unique Booking IDs": df["Booking ID"].nunique(),
    "Unique Customer IDs": df["Customer ID"].nunique(),
    "Missing Customer IDs": df["Customer ID"].isna().sum(),
    "Missing Pickup Locations": df["Pickup Location"].isna().sum(),
    "Missing Drop Locations": df["Drop Location"].isna().sum()
})

data_quality_summary

Total Rows                  150000
Total Columns                   21
Duplicate Rows                   0
Unique Booking IDs          148767
Unique Customer IDs         148788
Missing Customer IDs             0
Missing Pickup Locations         0
Missing Drop Locations           0
dtype: int64

##  Final Data Quality Summary

A final data quality summary is created to consolidate the key structural checks performed before data cleaning.

In [54]:
# Definition: This creates an independent copy of the raw dataset for cleaning.

cleaned_df = df.copy()

print("Raw dataset shape:", df.shape)
print("Working copy shape:", cleaned_df.shape)

#df -->raw/original dataset
#cleaned_df --> cleaning ke liye working dataset

#Hum aage se cleaning mostly cleaned_df par karenge.

Raw dataset shape: (150000, 21)
Working copy shape: (150000, 21)

## Create a Working Copy

A separate working copy is created so that the original raw dataset remains unchanged during the data cleaning process.

In [55]:
# Definition: This replaces non-applicable missing reason values with a meaningful category.


#NaN random missing data nahi hain. For example, completed ride ke liye cancellation reason applicable hi nahi hai.

#Isliye NaN ko blank chhodne ke bajay Not Applicable se replace karna useful rahega.

reason_columns = [
    "Reason for cancelling by Customer",
    "Driver Cancellation Reason",
    "Incomplete Rides Reason"
]

cleaned_df[reason_columns] = cleaned_df[reason_columns].fillna("Not Applicable")

cleaned_df[reason_columns].isna().sum()

Reason for cancelling by Customer    0
Driver Cancellation Reason           0
Incomplete Rides Reason              0
dtype: int64

##  Handle Missing Reason Values

Missing values in cancellation and incomplete ride reason columns are replaced with "Not Applicable" because these reasons do not apply to other booking outcomes.

In [56]:
# Definition: This replaces non-applicable missing payment methods with a meaningful category.

#Payment Method sirf Completed aur Incomplete rides mein available hai. 
# Cancelled aur No Driver Found rides mein payment method applicable nahi hai
#Isliye in NaN values ko Not Applicable se replace karna logical hai.

cleaned_df["Payment Method"] = cleaned_df["Payment Method"].fillna("Not Applicable")
cleaned_df["Payment Method"].isna().sum()

np.int64(0)

##  Handle Missing Payment Method

Missing payment method values are replaced with "Not Applicable" because payment information is not applicable to cancelled or no-driver-found rides.

In [57]:
#ratings sirf Completed rides ke liye available hain. Cancelled, Incomplete aur No Driver Found rides mein rating applicable nahi hai.

#Isliye NaN ko Not Applicable karna business-wise clear hoga. Lekin ek important point:
#  ratings numeric columns hain, isliye text "Not Applicable" daalne se unka numeric datatype kharab ho jayega.

#Isliye hum ratings ko numeric hi rakhenge aur missing values ko abhi NaN hi rehne denge. 
# Actual analysis mein ratings ko sirf available ratings ke saath use karenge.

# Definition: This verifies that rating columns remain numeric and their missing values are preserved.

print("Driver Ratings missing:", cleaned_df["Driver Ratings"].isna().sum())
print("Customer Rating missing:", cleaned_df["Customer Rating"].isna().sum())

print("Driver Ratings dtype:", cleaned_df["Driver Ratings"].dtype)
print("Customer Rating dtype:", cleaned_df["Customer Rating"].dtype)

#Yahan hum values change nahi kar rahe,
#sirf confirm kar rahe hain ki ratings numeric aur correctly preserved hain.

Driver Ratings missing: 57000
Customer Rating missing: 57000
Driver Ratings dtype: float64
Customer Rating dtype: float64

##  Preserve Missing Rating Values

Missing rating values are preserved because ratings are only applicable to completed rides and should remain numeric for statistical analysis.

In [58]:
# Definition: This verifies that missing booking values are preserved for non-applicable ride outcomes.


#Humne pehle verify kiya tha ki Booking Value sirf Completed aur Incomplete rides mein available hai, 
#jabki cancelled/no-driver rides mein missing hai. Isliye in missing values ko average ya 0 se fill karna incorrect hoga

print("Missing Booking Values:", cleaned_df["Booking Value"].isna().sum())
print("Booking Value dtype:", cleaned_df["Booking Value"].dtype)
#Abhi Booking Value mein koi filling nahi karni hai.

Missing Booking Values: 48000
Booking Value dtype: float64

##  Preserve Missing Booking Values

Missing booking values are preserved because they are structurally associated with cancelled and no-driver-found rides and do not represent missing revenue from completed trips.

In [59]:
# Definition: This verifies that missing ride distance values are preserved for non-applicable ride outcomes.


#Ride Distance sirf Completed aur Incomplete rides ke liye available hai. 
#Cancelled aur No Driver Found rides mein actual trip distance record nahi hua.

print("Missing Ride Distance:", cleaned_df["Ride Distance"].isna().sum())
print("Ride Distance dtype:", cleaned_df["Ride Distance"].dtype)

Missing Ride Distance: 48000
Ride Distance dtype: float64

In [60]:
#Yahan missing values ka reason clear hai: No Driver Found mein vehicle arrival time record nahi ho sakta.

#Isliye NaN ko mean/median se fill nahi karenge.
# Definition: This verifies that missing vehicle arrival time values are preserved.

print("Missing Avg VTAT:", cleaned_df["Avg VTAT"].isna().sum())
print("Avg VTAT dtype:", cleaned_df["Avg VTAT"].dtype)

Missing Avg VTAT: 10500
Avg VTAT dtype: float64

## Preserve Missing Vehicle Arrival Time Values

Missing average vehicle arrival time values are preserved because they are associated with rides where no driver was found and the metric is not applicable.

In [61]:
# Definition: This verifies that missing customer arrival time values are preserved.

print("Missing Avg CTAT:", cleaned_df["Avg CTAT"].isna().sum())
print("Avg CTAT dtype:", cleaned_df["Avg CTAT"].dtype)

Missing Avg CTAT: 48000
Avg CTAT dtype: float64

## Preserve Missing Customer Arrival Time Values

Missing average customer arrival time values are preserved because this metric is not applicable to cancelled and no-driver-found rides.

In [62]:
# Definition: This checks the data types of important numeric columns after cleaning.

numeric_columns = [
    "Avg VTAT",
    "Avg CTAT",
    "Booking Value",
    "Ride Distance",
    "Driver Ratings",
    "Customer Rating"
]

cleaned_df[numeric_columns].dtypes

Avg VTAT           float64
Avg CTAT           float64
Booking Value      float64
Ride Distance      float64
Driver Ratings     float64
Customer Rating    float64
dtype: object

## Numeric Data Type Validation

The numeric columns are validated after cleaning to ensure that their data types remain suitable for analysis.

In [63]:
# Definition: This verifies the data types of the date and time columns after cleaning.

print("Date dtype:", cleaned_df["Date"].dtype)
print("Time dtype:", cleaned_df["Time"].dtype)

Date dtype: datetime64[us]
Time dtype: object

##  Date and Time Validation

The date and time columns are validated after cleaning to ensure that they remain in appropriate datetime formats for time-based analysis.

In [64]:
# Definition: This removes leading and trailing whitespace only from text columns.

text_columns = [
    "Booking ID",
    "Booking Status",
    "Customer ID",
    "Vehicle Type",
    "Pickup Location",
    "Drop Location",
    "Reason for cancelling by Customer",
    "Driver Cancellation Reason",
    "Incomplete Rides Reason",
    "Payment Method"
]

for col in text_columns:
    cleaned_df[col] = cleaned_df[col].str.strip()

print("Text columns standardized successfully.")

Text columns standardized successfully.

In [65]:
# Definition: This combines the booking date and booking time into a single datetime value.

cleaned_df["Booking Datetime"] = pd.to_datetime(
    cleaned_df["Date"].astype(str) + " " + cleaned_df["Time"].astype(str)
)

print("Booking Datetime created successfully.")
print("Booking Datetime dtype:", cleaned_df["Booking Datetime"].dtype)

Booking Datetime created successfully.
Booking Datetime dtype: datetime64[us]

## Create Booking Datetime

The date and time columns are combined into a single datetime column to support time-based analysis and visualization.

In [66]:
# Summary:
# This code uses NumPy to group different booking statuses
# into standardized ride outcome categories for easier analysis.

# Definition: This creates a standardized ride outcome category using NumPy conditional logic.

conditions = [
    cleaned_df["Booking Status"] == "Completed",
    cleaned_df["Booking Status"] == "Incomplete",
    cleaned_df["Booking Status"] == "Cancelled by Customer",
    cleaned_df["Booking Status"] == "Cancelled by Driver",
    cleaned_df["Booking Status"] == "No Driver Found"
]

choices = [
    "Completed",
    "Incomplete",
    "Customer Cancelled",
    "Driver Cancelled",
    "No Driver Found"
]

cleaned_df["Ride Outcome Category"] = np.select(
    conditions,
    choices,
    default="Other"
)

cleaned_df["Ride Outcome Category"].value_counts()
#np.select() multiple conditions ko check karta hai.

Ride Outcome Category
Completed             93000
Driver Cancelled      27000
No Driver Found       10500
Customer Cancelled    10500
Incomplete             9000
Name: count, dtype: int64

##  Create Ride Outcome Category

The booking status is grouped into standardized ride outcome categories using NumPy conditional logic for easier analysis and visualization.

In [67]:
# Definition: This compares the original booking status with the new ride outcome category.

pd.crosstab(
    cleaned_df["Booking Status"],
    cleaned_df["Ride Outcome Category"]
)

Ride Outcome Category,Completed,Customer Cancelled,Driver Cancelled,Incomplete,No Driver Found
Booking Status,,,,,
Cancelled by Customer,0,10500,0,0,0
Cancelled by Driver,0,0,27000,0,0
Completed,93000,0,0,0,0
Incomplete,0,0,0,9000,0
No Driver Found,0,0,0,0,10500

In [68]:
# Definition: This extracts useful time-based features from the booking datetime.

cleaned_df["Booking Month"] = cleaned_df["Booking Datetime"].dt.month
cleaned_df["Booking Hour"] = cleaned_df["Booking Datetime"].dt.hour
cleaned_df["Booking Day"] = cleaned_df["Booking Datetime"].dt.day_name()

print("Time-based columns created successfully.")

cleaned_df[
    ["Booking Datetime", "Booking Month", "Booking Hour", "Booking Day"]
].head()

Time-based columns created successfully.

     Booking Datetime  Booking Month  Booking Hour Booking Day
0 2024-03-23 12:29:38              3            12    Saturday
1 2024-11-29 18:01:39             11            18      Friday
2 2024-08-23 08:56:10              8             8      Friday
3 2024-10-21 17:17:25             10            17      Monday
4 2024-09-16 22:08:00              9            22      Monday

## Create Time-Based Analysis Columns

Time-based columns are created from the booking datetime to support monthly, hourly, and day-of-week analysis.

In [69]:
cleaned_df.head()

,Date,Time,Booking ID,Booking Status,Customer ID,Vehicle Type,Pickup Location,Drop Location,Avg VTAT,Avg CTAT,...,Booking Value,Ride Distance,Driver Ratings,Customer Rating,Payment Method,Booking Datetime,Ride Outcome Category,Booking Month,Booking Hour,Booking Day
0,2024-03-23,12:29:38,"""CNR5884300""",No Driver Found,"""CID1982111""",eBike,Palam Vihar,Jhilmil,NaN,NaN,...,NaN,NaN,NaN,NaN,Not Applicable,2024-03-23 12:29:38,No Driver Found,3,12,Saturday
1,2024-11-29,18:01:39,"""CNR1326809""",Incomplete,"""CID4604802""",Go Sedan,Shastri Nagar,Gurgaon Sector 56,4.9,14.0,...,237.0,5.73,NaN,NaN,UPI,2024-11-29 18:01:39,Incomplete,11,18,Friday
2,2024-08-23,08:56:10,"""CNR8494506""",Completed,"""CID9202816""",Auto,Khandsa,Malviya Nagar,13.4,25.8,...,627.0,13.58,4.9,4.9,Debit Card,2024-08-23 08:56:10,Completed,8,8,Friday
3,2024-10-21,17:17:25,"""CNR8906825""",Completed,"""CID2610914""",Premier Sedan,Central Secretariat,Inderlok,13.1,28.5,...,416.0,34.02,4.6,5.0,UPI,2024-10-21 17:17:25,Completed,10,17,Monday
4,2024-09-16,22:08:00,"""CNR1950162""",Completed,"""CID9933542""",Bike,Ghitorni Village,Khan Market,5.3,19.6,...,737.0,48.21,4.1,4.3,UPI,2024-09-16 22:08:00,Completed,9,22,Monday

In [70]:
# Definition: This classifies each booking as a weekday or weekend.
#Ab hum Booking Day se ek aur useful business column banayenge: Weekday vs Weekend.

cleaned_df["Day Type"] = np.where(
    cleaned_df["Booking Day"].isin(["Saturday", "Sunday"]),
    "Weekend",
    "Weekday"
)

print("Day Type column created successfully.")

cleaned_df["Day Type"].value_counts()

Day Type column created successfully.

Day Type
Weekday    107060
Weekend     42940
Name: count, dtype: int64

##  Create Weekday and Weekend Category

The booking day is classified into weekday and weekend categories to support comparative ride activity analysis.

In [71]:
# Definition: This checks missing values and unique categories in the newly created columns.
#Ab ek final verification karenge ki jo naye columns humne banaye hain, 
# unmein koi unexpected/missing value nahi hai.

feature_columns = [
    "Booking Datetime",
    "Booking Month",
    "Booking Hour",
    "Booking Day",
    "Day Type",
    "Ride Outcome Category"
]

print("Missing values:")
print(cleaned_df[feature_columns].isna().sum())

print("\nUnique values:")
for col in feature_columns:
    print(f"{col}: {cleaned_df[col].nunique()}")

Missing values:
Booking Datetime         0
Booking Month            0
Booking Hour             0
Booking Day              0
Day Type                 0
Ride Outcome Category    0
dtype: int64

Unique values:
Booking Datetime: 149532
Booking Month: 12
Booking Hour: 24
Booking Day: 7
Day Type: 2
Ride Outcome Category: 5

##  Validate Feature-Engineered Columns

The newly created time-based and ride outcome columns are validated to ensure that they contain complete and consistent values.

In [72]:
# Definition: This summarizes the remaining missing values in the cleaned dataset.
#Ab cleaning ke baad poore cleaned_df ka final missing-value status check karenge.

#Important: iska purpose missing values ko blindly 0 ya mean se fill karna nahi hai. 
# Hum sirf verify karenge ki kaunse missing values abhi intentionally preserved hain.

missing_summary = cleaned_df.isna().sum()

missing_summary[missing_summary > 0]

Avg VTAT                        10500
Avg CTAT                        48000
Cancelled Rides by Customer    139500
Cancelled Rides by Driver      123000
Incomplete Rides               141000
Booking Value                   48000
Ride Distance                   48000
Driver Ratings                  57000
Customer Rating                 57000
dtype: int64

##  Final Missing Value Review

A final missing value review is performed after cleaning to confirm that remaining missing values are intentional and associated with non-applicable ride outcomes.

In [73]:
# Definition: This checks the final number of rows and columns in the cleaned dataset.

print("Final dataset shape:", cleaned_df.shape)
print("Total rows:", cleaned_df.shape[0])
print("Total columns:", cleaned_df.shape[1])

Final dataset shape: (150000, 27)
Total rows: 150000
Total columns: 27

## Final Dataset Shape

The final dataset shape is checked to confirm the number of rows and columns after data cleaning and feature engineering.

In [74]:
# Definition: This displays all columns available in the final cleaned dataset.
#Ab hum final dataset ke saare columns ek baar check karenge. 
# Isse confirm hoga ki original columns safe hain aur hamare naye feature columns bhi properly add ho gaye hain.

for i, col in enumerate(cleaned_df.columns, start=1):
    print(f"{i}. {col}")

1. Date
2. Time
3. Booking ID
4. Booking Status
5. Customer ID
6. Vehicle Type
7. Pickup Location
8. Drop Location
9. Avg VTAT
10. Avg CTAT
11. Cancelled Rides by Customer
12. Reason for cancelling by Customer
13. Cancelled Rides by Driver
14. Driver Cancellation Reason
15. Incomplete Rides
16. Incomplete Rides Reason
17. Booking Value
18. Ride Distance
19. Driver Ratings
20. Customer Rating
21. Payment Method
22. Booking Datetime
23. Ride Outcome Category
24. Booking Month
25. Booking Hour
26. Booking Day
27. Day Type

## Final Column Review

The final column list is reviewed to confirm that the original fields are preserved and the newly created analytical features are included.

In [75]:
# Definition: This saves the cleaned dataset as a separate CSV file.
#Ab hum cleaned dataset ko ek separate CSV file mein save karenge. 
# Original raw file ko bilkul touch nahi karenge.

cleaned_file_path = "../data/cleaned_urban_mobility.csv"

cleaned_df.to_csv(cleaned_file_path, index=False)

print("Cleaned dataset saved successfully.")
print("File:", cleaned_file_path)

PermissionError: [Errno 13] Permission denied: '../data/cleaned_urban_mobility.csv'

In [76]:
# Definition: This converts ride event indicators into consistent 0 and 1 values.
#Abhi inme NaN hai. Yahan NaN ka meaning event nahi hua hai, 
# isliye 0 karna logically correct hai. 1 already event ko represent karta hai.

binary_columns = [
    "Cancelled Rides by Customer",
    "Cancelled Rides by Driver",
    "Incomplete Rides"
]

cleaned_df[binary_columns] = cleaned_df[binary_columns].fillna(0).astype(int)

print("Binary columns standardized successfully.")

cleaned_df[binary_columns].value_counts()

Binary columns standardized successfully.

Cancelled Rides by Customer  Cancelled Rides by Driver  Incomplete Rides
0                            0                          0                   103500
                             1                          0                    27000
1                            0                          0                    10500
0                            0                          1                     9000
Name: count, dtype: int64

## Standardize Binary Ride Indicators

Binary ride indicator columns are standardized by replacing missing values with zero, where zero represents that the corresponding event did not occur.

In [77]:
# Definition: This saves the updated cleaned dataset to the CSV file.

#Ab jo binary columns humne 0/1 me convert kiye hain, un changes ko cleaned CSV me save karna zaroori hai. 
# Purani file overwrite kar denge, taaki SQL me jaane wala dataset latest cleaned version ho.

cleaned_file_path = "../data/cleaned_urban_mobility.csv"

cleaned_df.to_csv(cleaned_file_path, index=False)

print("Updated cleaned dataset saved successfully.")
print("File:", cleaned_file_path)

PermissionError: [Errno 13] Permission denied: '../data/cleaned_urban_mobility.csv'

##  Update the Cleaned Dataset

The cleaned dataset is saved again after standardizing binary ride indicator columns to ensure that the latest cleaning changes are included in the CSV file.

In [78]:
# Definition: This reloads the saved CSV and verifies its structure and binary indicator values.

#jo CSV humne save ki hai, usko dobara read karke check karenge ki file properly save hui hai aur 0/1 values bhi correctly store hui hain.

verified_df = pd.read_csv("../data/cleaned_urban_mobility.csv")

print("Verified dataset shape:", verified_df.shape)

print("\nBinary indicator values:")
print(verified_df[binary_columns].value_counts())

print("\nTotal missing values in binary columns:")
print(verified_df[binary_columns].isna().sum())

Verified dataset shape: (150000, 27)

Binary indicator values:
Cancelled Rides by Customer  Cancelled Rides by Driver  Incomplete Rides
0                            0                          0                   103500
                             1                          0                    27000
1                            0                          0                    10500
0                            0                          1                     9000
Name: count, dtype: int64

Total missing values in binary columns:
Cancelled Rides by Customer    0
Cancelled Rides by Driver      0
Incomplete Rides               0
dtype: int64

## Verify the Saved Cleaned Dataset

The saved cleaned dataset is reloaded to verify that the file was saved correctly and the cleaned binary indicators are preserved.

In [79]:
# Definition: This displays the final column names and data types before SQL import.

#Sabse pehle MySQL me import karne se pehle cleaned dataset ka final column structure dekh lenge, 
# taaki SQL table banate waqt har column ka naam aur type properly map kar saken.

sql_columns = pd.DataFrame({
    "Column": verified_df.columns,
    "Data Type": verified_df.dtypes.astype(str)
})

sql_columns

                                                              Column Data Type
Date                                                            Date       str
Time                                                            Time       str
Booking ID                                                Booking ID       str
Booking Status                                        Booking Status       str
Customer ID                                              Customer ID       str
Vehicle Type                                            Vehicle Type       str
Pickup Location                                      Pickup Location       str
Drop Location                                          Drop Location       str
Avg VTAT                                                    Avg VTAT   float64
Avg CTAT                                                    Avg CTAT   float64
Cancelled Rides by Customer              Cancelled Rides by Customer     int64
Reason for cancelling by Customer  Reason for cancelling by Customer       str
Cancelled Rides by Driver                  Cancelled Rides by Driver     int64
Driver Cancellation Reason                Driver Cancellation Reason       str
Incomplete Rides                                    Incomplete Rides     int64
Incomplete Rides Reason                      Incomplete Rides Reason       str
Booking Value                                          Booking Value   float64
Ride Distance                                          Ride Distance   float64
Driver Ratings                                        Driver Ratings   float64
Customer Rating                                      Customer Rating   float64
Payment Method                                        Payment Method       str
Booking Datetime                                    Booking Datetime       str
Ride Outcome Category                          Ride Outcome Category       str
Booking Month                                          Booking Month     int64
Booking Hour                                            Booking Hour     int64
Booking Day                                              Booking Day       str
Day Type                                                    Day Type       str

## Prepare Dataset for SQL Analysis

The cleaned dataset is reviewed before importing it into MySQL to identify the final columns that will be used for SQL analysis.

In [80]:
# Definition: This installs SQLAlchemy for connecting Python with SQL databases.

%pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (2.0.54)
Requirement already satisfied: greenlet>=1 in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (from sqlalchemy) (3.5.6)
Requirement already satisfied: typing-extensions>=4.6.0 in C:\Users\asus\AppData\Roaming\Python\Python314\site-packages (from sqlalchemy) (4.16.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [81]:
# Definition: This installs the MySQL connector required for Python-to-MySQL connections.

%pip install mysql-connector-python

Requirement already satisfied: mysql-connector-python in c:\Users\asus\AppData\Local\Programs\Python\Python314\Lib\site-packages (26.7.0)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 26.1.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [82]:
# Definition: This creates and tests a connection between Python and the MySQL database.

#Ab actual connection banayenge.
#— sirf check karenge ki Jupyter successfully MySQL ke urban_mobility database se connect ho raha hai.

import mysql.connector

connection = mysql.connector.connect(
    host="localhost",
    user="root",
    password="OmMysql@2026",
    database="urban_mobility"
)

print("MySQL connection successful!")

MySQL connection successful!

In [83]:
# Definition: This safely closes the active MySQL connection.

connection.close()

print("MySQL connection closed.")

MySQL connection closed.

In [84]:
# Definition: This uploads the cleaned Pandas DataFrame into a MySQL table.

#Hum Jupyter ke verified_df ko directly MySQL ke urban_mobility database me upload karenge.

#Is step me Pandas ka to_sql() use hoga. Ye automatically MySQL ke andar rides table create karke 150,000 rows upload karega.

from sqlalchemy import create_engine, URL

# Convert date and datetime columns to proper formats before SQL upload.
verified_df["Date"] = pd.to_datetime(verified_df["Date"])
verified_df["Booking Datetime"] = pd.to_datetime(verified_df["Booking Datetime"])

# Create the MySQL connection URL safely.
connection_url = URL.create(
    "mysql+mysqlconnector",
    username="root",
    password="OmMysql@2026",
    host="localhost",
    database="urban_mobility"
)

engine = create_engine(connection_url)

# Upload the DataFrame to MySQL.
verified_df.to_sql(
    "rides",
    con=engine,
    if_exists="replace",
    index=False
)

print("Cleaned dataset uploaded to MySQL successfully!")
print("Rows uploaded:", len(verified_df))

Cleaned dataset uploaded to MySQL successfully!
Rows uploaded: 150000

##  Upload the Cleaned Dataset to MySQL

The cleaned dataset is uploaded from Pandas to MySQL to create the rides table and make the data available for SQL analysis.

In [85]:
# Definition: This runs a SQL query from Python to count rows in the MySQL table.

from sqlalchemy import text

with engine.connect() as conn:
    result = conn.execute(text("SELECT COUNT(*) AS total_rows FROM rides"))
    total_rows = result.scalar()

print("Rows stored in MySQL:", total_rows)

Rows stored in MySQL: 150000

##  Verify the MySQL Data Import

The imported MySQL table is verified by checking the total number of rows stored in the rides table.